name: vato
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^0.3.4
  calendar_strip: 1.0.4
  barcode_scan2: 
  path_provider: 2.0.0
  percent_indicator: ^2.1.3
  provider: ^5.0.0
  http: ^0.13.0
  shared_preferences: 2.0.0
  line_icons: ^0.2.0
  sweetalert: ^0.0.1
  flutter_neumorphic: 3.1.0
  lottie: 1.1.0
  animated_text_kit: ^3.1.0
  folding_cell: 1.0.0
  rflutter_alert: ^1.1.0
  auto_size_text: ^2.1.0
  collection: 1.15.0
  countup: ^0.1.3
  flutter_animated_button: 1.1.0
  math_expressions: 2.0.2
  firebase_core: 1.2.0
  firebase_messaging: 10.0.0
  flutter_local_notifications: ^8.0.0
  awesome_notifications: ^0.0.6+10
  image_picker: ^0.8.3+3
  drawer_swipe: ^0.0.4
  timeline_tile: ^2.0.0
  google_fonts: ^2.1.0
  showcaseview: ^1.1.1
  date_range_picker: ^1.0.5
  csc_picker: ^0.2.5
  country_state_city_picker: 1.2.8
  pin_code_fields: ^7.3.0
  
  cupertino_stepper: ^0.2.0
  timeline_list2: ^0.1.0
  progress_timeline: ^0.0.5
  scrollable_positioned_list: ^0.1.10
  dropdown_search: ^1.0.4
  syncfusion_flutter_calendar: ^19.3.47
  unicorndial: ^1.1.5
  searchable_dropdown: ^1.1.3
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_datepicker: ^19.3.55
  group_button: ^3.3.1
  search_choices: ^2.0.14
  jiffy: ^4.1.0
  badges: ^2.0.2
  jwt_decode: ^0.3.1
  ntp: ^2.0.0
  dio: ^4.0.4
  flutter_svg: ^0.19.3
  hooks_riverpod: ^0.14.0+5
  flutter_secure_storage: ^5.0.2
  animated_progress_button: ^1.0.2+1
  fa_stepper: ^0.0.2
  google_maps_flutter: ^2.0.2

















dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/logoapp.png"
  image_path_ios: "assets/images/logoapp.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    
    - assets/images/
    - assets/scan.json
    - assets/logosplash.json
    - assets/logoff.json
flutter_intl:
  enabled: true