import 'package:flutter/material.dart';

abstract class Global {
  static const Color blue = const Color(0xFFDDE6E8);

  static const List lights = [


    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': true,
      'statusPM': true,
      'position': [0.2113,-0.38011],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': true,
      'statusPM': true,
      'position': [0.1710,-0.38011],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.1290,-0.38011],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.0868,-0.38011],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.0454,-0.38011],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.0054,-0.380],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [-0.0342,-0.380],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [-0.0740,-0.37800],
      'tile': 1,
    },
///////////////////////////////////////////////////////////
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.2113,-0.32221],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.1710,-0.3222],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.1290,-0.3222],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.0868,-0.3222],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.0454,-0.3222],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.0054,-0.3222],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [-0.0342,-0.3222],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [-0.0760,-0.3222],
      'tile': 1,
    },
    //////////////////////////////////////////////////////
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.2113,-0.26861],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.1710,-0.26861],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.1290,-0.26861],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.0868,-0.2681],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.0454,-0.2681],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [0.0056,-0.26680],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [-0.0339,-0.26720],
      'tile': 1,
    },
    {
      'location': 'Kitchen',
      'name': '',
      'statusAM': false,
      'statusPM': true,
      'position': [-0.0735,-0.2675],
      'tile': 1,
    }
  ];
}
